### PR TITLE
Use ollama chat instead of generate

### PR DESCRIPTION
**Pull request by yilmaz08**
This was a big change but here is a summary:

<details>
<summary>SQLite</summary>

### oterm/store/setup.py
* Removed `context` column
### oterm/store/chat.py
* Removed any `context` inside.
### oterm/store/store.py
* Removed `save_context()`
* Removed `context` element from `save_chat()`
* On unpackings (on lines 125, 126, 137, 139) removed context element
</details>

<details>
<summary>Widget</summary>

### oterm/app/widgets/chat.py
* Removed `context` parameter
* Replaced `context=context` with `history=[]` when creating the OllamaLLM
* Added a for loop to add `messages` list content to history with needed role.
* Removed the use of already removed function `save_context()` on line 139

#### Function action_edit_chat()
* Removed the `self.app.store.get_chat(self.db_id)` because it is only used for the context
* Removed `context=context` added `history=[]` when creating a new OllamaLLM
* Added a for loop to add `messages` list content to history with needed role.
</details>

<details>
<summary>OllamaLLM Class</summary>

### oterm/ollama.py
* Replaced `context: list[int]` with `history: list[string]` on __init__() parameters
* Replaced `self.context = context` with `self.history = history`
#### Function completion()
* Created system_prompt with necessary role using self.system
* Created user_prompt with necessary role using prompt (parameter)
* With an if loop insert `images` in the `user_prompt` unless the images are empty
* Append user prompt into the history
* Uses client.chat with parameter `messages=[system_prompt] + self.history`.
> I've not appended the system prompt directly in the history because when system prompt changes we would need to structure the history again

* get assistant/ollama response and append it to the history.
#### Function stream()
Changes are nearly the same as function completion()'s
</details>

<details>
<summary>Textual App</summary>

### oterm/app/oterm.py
* Remove `context="[]"` from function on_model_select()
* Remove `context` element from for loop in line 89 at function on_mount()
</details>

Currently it seems to work perfectly, but it needs a lot of testing before merging. \
It was a really big change and there might be some mistakes

I wanted to make the PR description long since there are a lot of things to explain and clarify. (it took 15+ minutes to write the description)

I've also added Arch Linux installation into the README.md in a seperate commit

Thank you all for this amazing project

### CODE REVIEW

**Comment by ggozad** [comment]
Hey Abdürrahim!
Thank you for your work, you are on a roll :)

I have been thinking about this for a while and it needs a bit of a discussion.
A bit of context (pun intended): Not so long ago, when I started `oterm` ollama did not support passing messages and only the `context` of the chat was made available after every call to `generate` through the API.
Essentially, the `context` retains the state/memory of the conversation and is restricted by the `num_context` parameter.
Passing messages was added later to the Ollama API, but the `context` is still available and can be used.
I would like to take a discussion with @jmorganca and the ollama people because I am not clear whether it would be preferable to use the `context` or the `messages` to retain the state of the conversation (or perhaps both): Using the context as is keeps things simple. However, using the messages would allow for more control, but needs for instance UI for how many messages should be kept, or a way to estimate through the size of the context.

I will try and understand this better and get back asap.

**Comment by yilmaz08** [comment]
As far as I know, when there is no regenerating and editing, using `generate` with context is nearly the same as using `chat` with message history.

However when using chat:
- You can go back and forth in the chat to get the response you want.
- You can request a regeneration of the last response.
- You can change LLM's message in order to manipulate responses. (not a suggestion lol)
- You can save space since you already save history of the chat and context won't be needed. (which is not a major difference)

These are not implemented in this PR, but with `chat` it is easier for next PRs to implement these features.

Popular tools like Open WebUI also use chat API for a more flexible and interactive experience.

In general: using `chat` is easier, more flexible and more storage efficient. `generate` is still a nice option but it is more limited for a chat tool like this.

This is just what I know about the case but we can discuss further if you have any other ideas.

Thank you so much :)

**Comment by yilmaz08** [comment]
I solved the conflicts

**Comment by ggozad** [comment]
This looks very well done, I am going to have a look and hopefully make a new release today.

**Comment by ggozad** [comment]
Hey @yilmaz08 I fixed the typing and made some minor improvements in https://github.com/ggozad/oterm/tree/feat/messages
Could you please have a look and let me know if you have any objections?

**Comment by ggozad** [comment]
Thanks again, very much appreciated.

**Pull request merged**
