### PR TITLE
add back binding for new_chat and delete chat

### PR DESCRIPTION
**Pull request by pekcheey**
the 2 key bindings seems to have been left out. Since it is trivial to add them in, here it is.

### CODE REVIEW

**Comment by ggozad** [comment]
Let me think a bit about this. I removed most of the bindings to avoid colliding with the bindings of certain widgets (I guess mostly the `TextArea`-based ones).  I am not sure I want to have exceptions, but I do see the point for these two. Could you check if there are any collisions with the default bindings in textual's docs?

**Comment by pekcheey** [comment]
from https://textual.textualize.io/widgets/text_area/#bindings
| Key(s)           | Description                                          |
| ---------------- | ---------------------------------------------------- |
| up               | Move the cursor up.                                  |
| down             | Move the cursor down.                                |
| left             | Move the cursor left.                                |
| ctrl+left        | Move the cursor to the start of the word.            |
| ctrl+shift+left  | Move the cursor to the start of the word and select. |
| right            | Move the cursor right.                               |
| ctrl+right       | Move the cursor to the end of the word.              |
| ctrl+shift+right | Move the cursor to the end of the word and select.   |
| home,ctrl+a      | Move the cursor to the start of the line.            |
| end,ctrl+e       | Move the cursor to the end of the line.              |
| shift+home       | Move the cursor to the start of the line and select. |
| shift+end        | Move the cursor to the end of the line and select.   |
| pageup           | Move the cursor one page up.                         |
| pagedown         | Move the cursor one page down.                       |
| shift+up         | Select while moving the cursor up.                   |
| shift+down       | Select while moving the cursor down.                 |
| shift+left       | Select while moving the cursor left.                 |
| shift+right      | Select while moving the cursor right.                |
| backspace        | Delete character to the left of cursor.              |
| ctrl+w           | Delete from cursor to start of the word.             |
| delete ,ctrl+d   | Delete character to the right of cursor.             |
| ctrl+f           | Delete from cursor to end of the word.               |
| ctrl+shift+k     | Delete the current line.                             |
| ctrl+u           | Delete from cursor to the start of the line.         |
| ctrl+k           | Delete from cursor to the end of the line.           |
| f6               | Select the current line.                             |
| f7               | Select all text in the document.                     |
| ctrl+z           | Undo.                                                |
| ctrl+y           | Redo.                                                |
| ctrl+x           | Cut selection or line if no selection.               |
| ctrl+c           | Copy selection to clipboard.                         |
| ctrl+v           | Paste from clipboard.                                |

it seems that the only conflict is ctrl+x
The more common binding for this is usually ctrl-w, but that is taken as well.

I propose ctrl+backspace as the binding for closing the window.

**Comment by ggozad** [comment]
Thanks, and sorry for the delay, holidays and all :)
Would you be so kind and update the README and add an entry to the changeling as well?

**Comment by pekcheey** [comment]
I've update the files. Please review if I'm doing it correctly.

**Comment by ggozad** [comment]
Thank you so much @pekcheey , happy holidays to you too!

**Pull request merged**
