### PR TITLE
Use correct ollama client in ChatEdit screen. Fix #76

### LINKED ISSUE #76: Environment variables are ignored in ChatEdit screen
The symptom is: User set a custom ollama URL using an environment variable and then accessed the ChatEdit screen. It does not use the customized url to fetch model list, which results in an exception (app crash).

In `oterm/app/chat_edit.py`, ollama is directly imported:

https://github.com/ggozad/oterm/blob/147cd2fa23d2cbcf725d565244ae25bd2f10d135/oterm/app/chat_edit.py#L5

https://github.com/ggozad/oterm/blob/147cd2fa23d2cbcf725d565244ae25bd2f10d135/oterm/app/chat_edit.py#L77

Here, it uses an ollama client created in ollama python library. This client always has the default host and port 127.0.0.1:11434

### PR DESCRIPTION
**Pull request by habaneraa**
A simple fix for issue #76 .

In addition, I think maybe we can extract these local variables to a global `client` variable, which naturally functions as a singleton object.

https://github.com/ggozad/oterm/blob/147cd2fa23d2cbcf725d565244ae25bd2f10d135/oterm/ollama.py#L22-L24

https://github.com/ggozad/oterm/blob/147cd2fa23d2cbcf725d565244ae25bd2f10d135/oterm/ollama.py#L39-L41

### CODE REVIEW

**Review by ggozad — CHANGES_REQUESTED** [review]
Thank you for this!
Some (minor) comments:
I am happy with a singleton here but then having the OllamaLLM in parallel seems like a missed opportunity. So I would either:
1) move the functionality for `list`, `show` to OllamaLLM and create a singleton out of it.
or 2) remove OllamaLLM altogether and use your singleton directly.
Happy to discuss if you think differently, I don't have strong opinions on this.

Could you also add an entry to  `CHANGES.txt` with your username and a description?
As soon as we merge I will release :)

**Comment by ggozad** [comment]
And of course I should have coffee before opening my mouth...
We don't want the singleton here for OllamaLLM. Perhaps best if `list`, `show` etc become static methods on `OllamaLLM`?

**Comment by habaneraa** [comment]
You are right. Static methods are absolutely better here.

Note that I kept those "list" and "show" requests to be synchronous. Just like before. I observed that the app will result in a strange NoScreen exception if the async `on_mount()` method of `ChatEdit` finishes late... Currently I have no idea why a slow request would lead to NoScreen exception. Will investigate this later. Anyway this PR works well.

**Comment by ggozad** [comment]
Thank you so much, this looks great! I am way from a computer atm, but will merge and release tomorrow!

**Review by ggozad — APPROVED** [review]

**Pull request merged**
